spring:
  datasource:
    url: jdbc:h2:file:/tmp/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

feed:
  url: https://www.youtube.com/feeds/videos.xml?channel_id=UCDre3E87RvZbrwExk3Flfug
  cron: "0 0 0 * * ?"  # Every day at midnight
  