name: Build with JIB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Build with JIB
      run: mvn compile jib:dockerBuild -Dimage=ghcr.io/granja-caimito/youtube-pubsub:${{ github.run_number }}
      
    - name: Push image to GitHub Container Registry
      run: docker push ghcr.io/granja-caimito/youtube-pubsub:${{ github.run_number }}
      